# Generated by Django 6.0.4 on 2026-04-24 17:47

import django.db.models.deletion
import reportes.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('domicilio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTransportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('patente', models.CharField(max_length=20)),
                ('transporte', models.CharField(choices=[('CAMION', 'Camión'), ('SEMIREMOLQUE', 'Semirremolque'), ('CAMIONETA', 'Camioneta'), ('FURGONETA', 'Furgoneta'), ('PARTICULAR', 'Particular')], default='CAMION', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidas', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remito_recepcion', models.CharField(editable=False, max_length=255, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('patente_reporte', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.empleado')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.usuariotransportista')),
            ],
        ),
        migrations.CreateModel(
            name='PiezaRechazada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('imagen', models.ImageField(blank=True, null=True, storage=reportes.storage_backend.AzureMediaStorage(), upload_to='images-piezas-rechazadas/')),
                ('categoria_dano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.categoriadano')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.pieza')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas_rechazadas', to='reportes.reportedano')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.rol'),
        ),
    ]
