# Generated by Django 6.0.4 on 2026-05-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedano',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
